#!/bin/env python
import argparse
import logging

from xstats.daemon import aggregator

FORMAT = '[%(asctime)-15s] [%(name)s] %(message)s'
logging.basicConfig(format=FORMAT, level = logging.DEBUG)
logger = logging.getLogger(__name__)

def main():
    parser = argparse.ArgumentParser(description = "xStats Server")
    parser.add_argument("--port", "-p",
                        type    = int,
                        default = 13337,
                        help    = "Port to listen on")

    args = parser.parse_args()

    logger.debug("Starting xStats Server...")
    aggregator.start(args.port)
    logger.debug("Exiting...")

if __name__ == "__main__":
    main()
