#!/bin/env python
import argparse
import logging

from xstats.daemon import reporter
from xstats.daemon.shared import setup_logging; setup_logging()

logger = logging.getLogger(__name__)

def main():
    parser = argparse.ArgumentParser(description = "xStats Reporter")
    parser.add_argument("--port", "-p",
                        type    = int,
                        default = 13337,
                        help    = "Port to connect to")
    parser.add_argument("host",
                        default = "localhost",
                        help    = "Host to connect to")

    args = parser.parse_args()

    logger.debug("Starting xStats Reporter")
    reporter.start((args.host, args.port))
    logger.debug("Exiting...")

if __name__ == "__main__":
    main()
