#!/bin/env python

import sys
import logging

from xstats.daemon.network import Server
from xstats.daemon import reporter, aggregator

FORMAT = '%(asctime)-15s %(message)s'
logging.basicConfig(format=FORMAT, level = logging.DEBUG)

logger = logging.getLogger(__name__)

if __name__ == "__main__":
    if sys.argv[1] == "client":
        try:
            logger.debug("Starting reporter...")
            client = reporter.start(sys.argv[2:])
            logger.debug("Joining greenlet...")
            client.finished.wait()
            logger.debug("Exiting...")
        except KeyboardInterrupt:
            client.disconnect()
            client.finished.wait()
    elif sys.argv[1] == "server":
        server = aggregator.start(sys.argv[2])
        logger.debug("Join greenlet...")
        server.serverGreenlet.join()
        logger.debug("Exiting...")
