#!/bin/env python
import sys
import logging

from xstats.daemon import reporter, aggregator

FORMAT = '[%(asctime)-15s] [%(name)s] %(message)s'
logging.basicConfig(format=FORMAT, level = logging.DEBUG)

logger = logging.getLogger(__name__)

def main():
    if len(sys.argv) < 2 or sys.argv[1] not in ('client', 'server'):
        return 1

    logger.debug("Starting %s..." % sys.argv[1])

    if sys.argv[1] == "client":
        reporter.start(sys.argv[2:])
    elif sys.argv[1] == "server":
        aggregator.start(sys.argv[2])

    logger.debug("Exiting...")
    return 0

if __name__ == "__main__":
    exitCode = main()
    if exitCode != 0:
        print "Syntax: ./xstats server <port>"
        print "                 client <address> <port>"

    sys.exit(exitCode)
