#!/bin/env python
import argparse
import logging

from xstats.daemon import aggregator
from xstats.daemon.shared import setup_logging; setup_logging()

logger = logging.getLogger(__name__)

def main():
    parser = argparse.ArgumentParser(description = "xStats Server")
    parser.add_argument("--port", "-p",
                        type    = int,
                        default = 13337,
                        help    = "Port to listen on")

    args = parser.parse_args()

    logger.debug("Starting xStats Server...")
    aggregator.start(args.port)
    logger.debug("Exiting...")

if __name__ == "__main__":
    main()
